### ISSUE TITLE
Define are double

### ISSUE THREAD

**Issue by OstertagM** [closedcube/ClosedCube_SHT31D_Arduino#1]
If i want to use SHT31D and opt3001 at same board I have defined double declaration please change it that I can use more board from your lib at the same micro controller.

 In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:22:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_OPT3001_Arduino-master\src/ClosedCube_OPT3001.h:48:13: error: redeclaration of 'NO_ERROR'

  NO_ERROR = 0,

             ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:19:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_SHT31D_Arduino-master\src/ClosedCube_SHT31D.h:110:2: note: previous declaration 'SHT31D_ErrorCode NO_ERROR'

  NO_ERROR = 0,

  ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:22:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_OPT3001_Arduino-master\src/ClosedCube_OPT3001.h:49:19: error: redeclaration of 'TIMEOUT_ERROR'

  TIMEOUT_ERROR = -100,

                   ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:19:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_SHT31D_Arduino-master\src/ClosedCube_SHT31D.h:113:2: note: previous declaration 'SHT31D_ErrorCode TIMEOUT_ERROR'

  TIMEOUT_ERROR = -102,

  ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:22:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_OPT3001_Arduino-master\src/ClosedCube_OPT3001.h:52:27: error: redeclaration of 'WIRE_I2C_DATA_TOO_LOG'

  WIRE_I2C_DATA_TOO_LOG = -10,

                           ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:19:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_SHT31D_Arduino-master\src/ClosedCube_SHT31D.h:121:2: note: previous declaration 'SHT31D_ErrorCode WIRE_I2C_DATA_TOO_LOG'

  WIRE_I2C_DATA_TOO_LOG = -10,

  ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:22:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_OPT3001_Arduino-master\src/ClosedCube_OPT3001.h:53:39: error: redeclaration of 'WIRE_I2C_RECEIVED_NACK_ON_ADDRESS'

  WIRE_I2C_RECEIVED_NACK_ON_ADDRESS = -20,

                                       ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:19:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_SHT31D_Arduino-master\src/ClosedCube_SHT31D.h:122:2: note: previous declaration 'SHT31D_ErrorCode WIRE_I2C_RECEIVED_NACK_ON_ADDRESS'

  WIRE_I2C_RECEIVED_NACK_ON_ADDRESS = -20,

  ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:22:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_OPT3001_Arduino-master\src/ClosedCube_OPT3001.h:54:36: error: redeclaration of 'WIRE_I2C_RECEIVED_NACK_ON_DATA'

  WIRE_I2C_RECEIVED_NACK_ON_DATA = -30,

                                    ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:19:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_SHT31D_Arduino-master\src/ClosedCube_SHT31D.h:123:2: note: previous declaration 'SHT31D_ErrorCode WIRE_I2C_RECEIVED_NACK_ON_DATA'

  WIRE_I2C_RECEIVED_NACK_ON_DATA = -30,

  ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:22:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_OPT3001_Arduino-master\src/ClosedCube_OPT3001.h:55:27: error: redeclaration of 'WIRE_I2C_UNKNOW_ERROR'

  WIRE_I2C_UNKNOW_ERROR = -40

                           ^

In file included from C:\Users\Matthias\Documents\Arduino\MQQT-SHT35-Single\MQQT-SHT35-Single.ino:19:0:

C:\Users\Matthias\Documents\Arduino\libraries\ClosedCube_SHT31D_Arduino-master\src/ClosedCube_SHT31D.h:124:2: note: previous declaration 'SHT31D_ErrorCode WIRE_I2C_UNKNOW_ERROR'

  WIRE_I2C_UNKNOW_ERROR = -40

  ^

exit status 1
Fehler beim Kompilieren für das Board WeMos D1 R2 & mini.

**Comment by closedcube** [comment]
Hello,

Thank you for the reporting this issue, we will review duplicate/conflict codes in our libraries.

Kind regards,
ClosedCube

**Comment by closedcube** [comment]
New release 1.5.0
