### ISSUE TITLE
No need to wait after Wire.requestFrom() and no beginTransmission() or endTransmission needed.

### ISSUE THREAD

**Issue by Koepel** [closedcube/ClosedCube_SHT31D_Arduino#2]
When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received bytes are waiting in a buffer in the Wire library. There is nothing to wait for to read those bytes.

In the file "ClosedCube_SHT31D.cpp" the waiting with the loop and the delay can be removed.

This:
```
        int counter = 0;
	while (Wire.available() < numOfBytes)
	{
		counter++;
		delay(50);
		if (counter > 100)
			return TIMEOUT_ERROR;
        }
```
can be replaced by this:
```
	if (Wire.available() != numOfBytes)
	{
        	return some_kind_of_bus_ERROR;  // fill in your own error code
        }
```

The Wire.beginTransmission() and Wire.endTransmission() are only used when writing data. They should not be used before and after the Wire.requestFrom(). They can be removed in the function ClosedCube_SHT31D::read().

**Comment by closedcube** [comment]
Hello,

Thank you for your suggestions.

We assumed that there might be delays (depends from a sensir mode, SHT3X-D response preparation,s I2C communications etc.)  and would prefer to wait a bit rathan than report an error immediately.

Kind Regards,
ClosedCube

**Comment by Koepel** [comment]
Are you saying that you keep the (minor) bug ?
The Wire.requestFrom() does the I2C transaction on the I2C bus. After that, the Wire.available() and Wire.read() only deal with the buffer in the Wire library. The Wire.available() and Wire.read() have no part in the sensor response or I2C communications.
There is no reason to wait a bit. There is nothing to wait for.

**Comment by closedcube** [comment]
The expecting data might be not available immediately after a request, especially if some measurement required for a specific sensor, so we tried to minimise user-error handling and implemented these in the library.

We will have a look into requestFrom inside begin/end transmission block , thank you for the pointing to this issue.

**Comment by Koepel** [comment]
You assume that data might not be immediately available, but that is not how it is.
The Wire.requestFrom() does everything: start; send I2C address; check for acknowledge; read data; send acknowledge; read more data; send stop. Only after that it returns.
When the Wire.requestFrom() returns, the I2C transaction has completely finished. I really has, seriously. Look into it. If you don't believe me, try to find official Arduino documentation that tells to wait. See also Nick Gammon's page about i2c: http://www.gammon.com.au/i2c (search for "does not return").

If the sensor is slow, some delay before the Wire.requestFrom() might be needed. I'm only talking here about the not needed delay between Wire.requestFrom() and Wire.available()/Wire.read().

**Comment by closedcube** [comment]
New release 1.5.0
