### ISSUE TITLE
SHT3XD error: -20

### ISSUE THREAD

**Issue by pidiet** [closedcube/ClosedCube_SHT31D_Arduino#4]
Hello,

I'm using shtshow from boneskuell (https://github.com/boneskull/shtshow) which is using this library.

I have the issue that I get this error (https://github.com/boneskull/shtshow/issues/3):

`SHT3XD error: -20`

And I have no idea what it means? Is there any documentation? Thank's a lot!

**Comment by closedcube** [comment]
Hello,

That’s error related to I2C communication issue. In the most cases, a sensor has wrongly connected to your board.

We would suggest to run a simple script aka I2CScanner.

ClosedCube Support Team

**Comment by pidiet** [comment]
Hey @closedcube 

thank's for your fast feedback. I will look deeper into my hardware!
